server:
  port: 8081
spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: springboot
    password: springboot
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      detault-zone: http://localhost:8761/eureka
info:
  app:
    description: This is auth service on spring boot application
    name: Auth Service
    version: 1.0.0
